spring:
  application:
    name: reference-service

server:
  port: 8080

aws:
  region: us-east-1
  dynamodb:
    table-name: references
  sqs:
    queue-url: ${EVENT_QUEUE_URL}

logging:
  level:
    root: INFO
    com.skillvo.reference: DEBUG 